config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kinds</h1>

<table id="kinds-table">
  <thead>
    <tr>
      <th><%= Kind.human_attribute_name("description")%></th>
      <th>Mostrar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to 'Show', kind %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kind', new_kind_path %>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>