config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Fixed navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Inicio",home_index_path,class:'nav-link active'%></li>
          <li class="nav-item"><%= link_to "Contatos",contacts_path,class:'nav-link'%></li>
          <li class="nav-item"><%= link_to "Tipos",kinds_path,class:'nav-link'%></li>
          <li class="nav-item"><%= link_to "Endereços",addresses_path,class:'nav-link'%></li>
          <li class="nav-item"><%= link_to "Telefones",phones_path,class:'nav-link'%></li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" placeholder="Search" aria-label="Search" type="text">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>