config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :contact_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table id="addresses-table">
  <thead>
    <tr>
      <th><%=Address.human_attribute_name("street")%></th>
      <th><%=Address.human_attribute_name("city")%></th>
      <th><%=Address.human_attribute_name("state")%></th>
      <th><%=Address.human_attribute_name("contact")%></th>
      <th>Mostrar</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.contact %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @address.contact %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>